In [40]:
import numpy as np

## NumPy Array Initialization

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
arr = np.zeros([4, 3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.ones(3)
print(arr)

In [ ]:
arr = np.empty([2, 1])
print(arr)

### Comparing np.zeros & np.empty

In [41]:
size=100000000
%timeit np.zeros(size)

53 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
%timeit a = np.empty(size); a[:] = 0

854 ms ± 87.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### There is an advantage of using pre-defined NumPy functions

In [44]:
# What happens in np.empty initialization
print(np.empty(10))

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]


### Declaring array over a range of values

In [ ]:
arr=np.arange(2, 10, 3)
print(arr)

In [ ]:
arr = np.array([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]], [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])
print(arr)

In [ ]:
print("Array has", arr.ndim, "dimensions.")
print("Array has", arr.size, "elements.")
print("Array has shape", arr.shape)

In [ ]:
arr.reshape(12, 2)

### Use of reshape

In [18]:
threeByFour = np.arange(12).reshape(3, 4)
print(threeByFour)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Deleting certain values, rows

In [19]:
threeByFour = np.arange(12).reshape(3, 4)
print(np.delete(threeByFour, 0, axis=0))

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# Multidimensioned arrays will first be flattened
threeByFour = np.arange(12).reshape(3, 4)
print(np.delete(threeByFour, 0))

[ 1  2  3  4  5  6  7  8  9 10 11]


In [21]:
# We can delete a certain slice
threeByFour = np.arange(12).reshape(3, 4)
print(np.delete(threeByFour, slice(0, 2, 1),axis=1))

[[ 2  3]
 [ 6  7]
 [10 11]]


In [22]:
# Another syntax for deleting a slice
threeByFour = np.arange(12).reshape(3, 4)
print(np.delete(threeByFour, np.s_[0:2:1],axis=1))

[[ 2  3]
 [ 6  7]
 [10 11]]


In [23]:
readWeather = np.loadtxt('weather.txt', 
                         dtype={'names': ('month', 'high', 'low'), 
                                'formats':('S10', 'i4', 'i4')}, 
                         delimiter=",")
print(readWeather)

[(b'September', 24, 14) (b'October', 15,  8) (b'November',  9,  2)
 (b'December',  3, -3)]


### Broadcasting

#### Adding or multiplying a single value

In [24]:
arr = np.arange(10)
b   = 3
add = b + arr
print(add)

[ 3  4  5  6  7  8  9 10 11 12]


#### Operations are element-wise

In [26]:
a = np.array([4, 2, 3, 1])
b = np.array([6, 4, 0, 1])
print(a*b)

[24  8  0  1]


#### Dealing with different shapes of arrays: does it work?

In [27]:
a = np.arange(6).reshape(6, 1)
b = np.arange(6).reshape(3, 1, 2)
c = a + b

In [28]:
print(np.shape(c))

(3, 6, 2)


In [30]:
print(c)

[[[ 0  1]
  [ 1  2]
  [ 2  3]
  [ 3  4]
  [ 4  5]
  [ 5  6]]

 [[ 2  3]
  [ 3  4]
  [ 4  5]
  [ 5  6]
  [ 6  7]
  [ 7  8]]

 [[ 4  5]
  [ 5  6]
  [ 6  7]
  [ 7  8]
  [ 8  9]
  [ 9 10]]]


In [29]:
a = np.arange(6).reshape(1, 6)
b = np.arange(6).reshape(3, 1, 2)
c = a + b

ValueError: operands could not be broadcast together with shapes (1,6) (3,1,2) 

### Splitting up arrays

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [17]:
# horizontal splitting across the rows
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Concatenating arrays

In [35]:
a = np.zeros(4).reshape(2, 2)
b = np.ones(6).reshape(3, 2)
c = np.concatenate((a, b))
print(c)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
a = np.zeros(4).reshape(2, 2)
b = np.ones(6).reshape(3, 2)
c = np.concatenate((a, b), axis=1)
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

### Masking example

In [52]:
a = np.linspace(0, 95, 20).reshape(5, 4)
mask1 = a % 2
mask2 = a > 10
mask3 = a < 80

In [53]:
result = a * mask1 * mask2 * mask3
print(result)

[[ 0.  0.  0. 15.]
 [ 0. 25.  0. 35.]
 [ 0. 45.  0. 55.]
 [ 0. 65.  0. 75.]
 [ 0.  0.  0.  0.]]


In [54]:
values = np.nonzero(result)
std = np.std(result)
avg = np.mean(result)
print("There are ", np.count_nonzero(result), "elements.")
print("The average is", avg, "and the stdev is", std)

There are  7 elements.
The average is 15.75 and the stdev is 24.508926945094924


### Reading and writing the results to a file

In [56]:
np.savetxt("filtered_arr.csv", result, delimiter=",")
data = np.loadtxt("filtered_arr.csv", delimiter=",")
print(data)

[[ 0.  0.  0. 15.]
 [ 0. 25.  0. 35.]
 [ 0. 45.  0. 55.]
 [ 0. 65.  0. 75.]
 [ 0.  0.  0.  0.]]


### Example: Rewriting empty values with mean grades

In [5]:
# Students down the rows, individual grades along the columns
grades = np.loadtxt("grades.csv", delimiter=",")
print(grades)

[[89. 84. 68. 87. 71. 96. 79. 83. 60. 68.]
 [89. 86. 83. 71. 62. 99. 72. 61. 63. 82.]
 [99.  0. 74. 92. 76. 90. 96. 98. 62. 91.]
 [72. 90. 99. 64. 74. 87. 83. 63. 66. 97.]
 [63. 88. 77.  0. 97. 78. 96. 93. 64. 74.]
 [84. 99. 75. 88. 85. 75. 92.  0. 93. 60.]
 [91. 61. 98. 71. 71. 71.  0.  0. 89. 72.]
 [78. 73. 83. 94. 90. 88. 67. 99. 65. 72.]
 [88. 69. 72. 70. 75. 87. 63.  0. 61. 83.]
 [70. 75. 81. 77. 63. 77. 62. 70. 67. 69.]]


In [6]:
# There is a problem here! We include the zeros in the average calculation
averages = np.mean(grades, axis=1)
print(averages)

[78.5 76.8 77.8 79.5 73.  75.1 62.4 80.9 66.8 71.1]


In [25]:
num_nonzero  = np.count_nonzero(grades, axis=1)       # count number of non-zero elements per row
sum_line     = np.sum(grades, axis=1)                 # find sum over all rows
inds         = np.where(grades==0)                    # get indices where values are 0
grades[inds] = np.take(sum_line/num_nonzero, inds) # replaces the values at the index by the new average

In [26]:
print(grades)
print("Memory size of array in bytes: ", grades.size * grades.itemsize)

[[89.  84.  68.  87.  71.  96.  79.  83.  60.  68. ]
 [89.  86.  83.  71.  62.  99.  72.  61.  63.  82. ]
 [99.  76.8 74.  92.  76.  90.  96.  98.  62.  91. ]
 [72.  90.  99.  64.  74.  87.  83.  63.  66.  97. ]
 [63.  88.  77.  79.5 97.  78.  96.  93.  64.  74. ]
 [84.  99.  75.  88.  85.  75.  92.  80.9 93.  60. ]
 [91.  61.  98.  71.  71.  71.  78.  80.9 89.  72. ]
 [78.  73.  83.  94.  90.  88.  67.  99.  65.  72. ]
 [88.  69.  72.  70.  75.  87.  63.  80.9 61.  83. ]
 [70.  75.  81.  77.  63.  77.  62.  70.  67.  69. ]]
Memory size of array in bytes:  800
